### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tobq** [Adversities/Tanji#1]
How do you actually run this

**Comment by Adversities** [comment]
Well don't download the source-code, download the release one: https://github.com/Tangerinos/Tanji/releases
Click "Tanji.zip", after download extract on any folder or desktop and run Tanji.exe as admin, when it asks you to install certifieds please click "yes"

**Comment by tobq** [comment]
I realised after - Where can I get the sulakore folder you used to buiild this, so I can actually work on this.

**Comment by Adversities** [comment]
Man, there's Sulakore's source... /Adversities/Sulakore

**Comment by Speaqer** [comment]
It's in Tangerinos/Sulakore
